name: Auto Request Review

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      - name: Auto request review
        uses: necojackarc/auto-request-review@v0.7.0
        with:
          token: ${{ secrets.AUTO_REQUEST_REVIEW_SECRET }}
